level5/learning_users/basic_app/urls.py
from django.urls import path
from . import views


app_name = 'basic_app'

urlpatterns = [
    path('registration/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
]

level5/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

level5/learning_users/basic_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # portfoilio
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

level5/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level5/learning_users/basic_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .forms import UserForm, UserProfileInfoForm


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors, profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Your account is not active')
        else:
            print('Wrong data')
            print(f"{username} not found or password is incorrect")
    else:
        return render(request, 'basic_app/login.html')

level5/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">

            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                <li><a class="navbar-link" href="#">{{ user.username }}</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
            {% endif %}

        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>


</body>
</html>

level5/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
    <h1>Django level 5</h1>
    </div>
{% endblock %}

level5/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please, log in: </h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:
                <input type="text" placeholder="enter username" name="username"></label>

            <label for="password">Password:
                <input type="password" name="password"></label>

            <input type="submit" name="login" value="login">

        </form>
    </div>
{% endblock %}

level5/learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registration!</h1>
        {% else %}
            <h1> Register here! </h1>
            <h3>Fill out the form: </h3>
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="register">


            </form>
        {% endif %}
    </div>
{% endblock %}